#!/bin/bash
DIR=$(dirname $BASH_SOURCE)
VENV="${DIR}/matrix-venv/bin/activate"
if [ ! -f "${VENV}" ]
then
    python3 -m venv "${DIR}/matrix-venv"
    . "${VENV}"
fi

(cd $DIR; git submodule update --init --recursive)
pip install -r "${DIR}/requirements.txt"

cp "${DIR}/config/config.py" "${DIR}/hdmi_matrix_control/hdmi_matrix_controller/config.py"
(
    . "${VENV}"
    cd "${DIR}/hdmi_matrix_control" || exit 2
    rm nohup.out
    nohup python -m hdmi_matrix_controller.daemon & #2>/dev/null 1>/dev/null &
    FLASK_APP=hdmi_matrix_controller.web nohup flask run --host 127.0.0.1 & #2>/dev/null 1>/dev/null &
) || echo "[ERROR] Failed to start HDMI matrix"

